language: node_js
node_js:
  - 12
cache: npm
install:
  - npm ci
services:
  - postgresql
before_script:
  - psql -c 'create database edventure;' -U postgres
  - psql "dbname=edventure" -a -f init.pgsql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - DB_USER=postgres
    - DB_HOST=localhost
    - DB_DATABASE=edventure
    - DB_PORT=5432
    - DB_PASSWORD=
    - TEST_DB_USER=postgres
    - TEST_DB_HOST=localhost
    - TEST_DB_DATABASE=edventure
    - TEST_DB_PORT=5432
    - TEST_DB_PASSWORD=
script:
  - npm test
deploy:
  matrix:
    - cleanup: false
      provider: heroku
      api_key:
        secure: r7xlqiNUJaxmWB8BTt/qWPcFBg8D6ZN25y7Xfs5YzIvL4D+9yb5l9M9o+AMV9f6JLGlsntDxm6Oeh2gHkAsqpOcmjS7dMSS1GujwO5By9dPv3czVN3JQI5WlnZYHDIVKae/eSGm6vrX6GppiNRkxWebJ0Z8Km3SbknIONcXrWMXwE/OROBUeX/ELCDPkNXUI/qMaGc5oXsCBIVH4vmtfbVVsGotXpHPbsPH/a/uqUTeH/1HrWxbqXVsLDy6l1qEE3lLnjMECfwHoNriCd6Hq1KaTUIL7Q/OAZ/yUBeqvXHRtOKSeQLuhQomR5nemvXlePsP69VjqtQSnA2hsBsGg8dRNcdent0ePe9+36QuC6LlWISndX6Typ4DluVxdfftSSFzsSC2ufoCVLqRVZj9dqmVSOCrYn0k80E1QPoT7h1w1z3lDTN2z849n5a3/lapyrM+I+kSuNXqJhQwWKGEDpUmNZ9lSwW3GNj489HPTHBt/inhbuxMB3jr0kJvsMk+rqDeniFlLm/qv01uU8GFrsE/4Rh2im5neMsHhbCgcTnOtlyN0sO+cRN7LldQ1YSKEE4o9yjLOpYz4A5/YAbrbT74vC1T0Rsi93BdY+yan2GtwAovwpzg3PjfucEOIqxMqLU96PHdxv/hmxQbdCu6JyJ6YZ946tqwTOl+jSVTfEl0=
      app: dev-power-sophia
      on:
        repo: BuildForSDG/Team-032-Product
        branch: develop
