const { body } = require('express-validator');

module.exports = [
  body('name')
    .trim(' ')
    .notEmpty()
    .withMessage('Input a user password')
    .isLength({ max: 30, min: 2 })
    .withMessage('Length must not exceed 30 characters')
    .escape(),
  body('town')
    .trim(' ')
    .notEmpty()
    .withMessage('Input a user password')
    .isLength({ max: 30, min: 2 })
    .withMessage('Length must not exceed 30 characters')
    .escape(),
  body('lga')
    .trim(' ')
    .notEmpty()
    .withMessage('Input a user password')
    .isLength({ max: 30, min: 2 })
    .withMessage('Length must not exceed 30 characters')
    .escape(),
  body('state')
    .trim(' ')
    .notEmpty()
    .withMessage('Input a user password')
    .isLength({ max: 30, min: 2 })
    .withMessage('Length must not exceed 30 characters')
    .escape(),
  body('country')
    .trim(' ')
    .notEmpty()
    .withMessage('Input a user password')
    .isLength({ max: 30, min: 2 })
    .withMessage('Length must not exceed 30 characters')
    .escape(),
  body('totalPopulation')
    .trim(' ')
    .notEmpty()
    .withMessage('Total population estimate must be provided')
    .isInt({ gt: 0 })
    .withMessage('Population cannot be below 0')
    .escape(),
  body('childrenPopulation')
    .optional()
    .trim(' ')
    .notEmpty()
    .withMessage('Empty data cannot be processed')
    .isInt({ gt: 0 })
    .withMessage('Population cannot be below 0')
    .escape(),
  body('youthPopulation')
    .optional()
    .trim(' ')
    .notEmpty()
    .withMessage('Empty data cannot be processed')
    .isInt({ gt: 0 })
    .withMessage('Population cannot be below 0')
    .escape(),
  body('middleAgedPopulation')
    .optional()
    .trim(' ')
    .notEmpty()
    .withMessage('Empty data cannot be processed')
    .isInt({ gt: 0 })
    .withMessage('Population cannot be below 0')
    .escape(),
  body('elderlyPopulation')
    .optional()
    .trim(' ')
    .notEmpty()
    .withMessage('Empty data cannot be processed')
    .isInt({ gt: 0 })
    .withMessage('Population cannot be below 0')
    .escape()
];
